## @file
# File templates/pr-gate-build-job.yml
#
# template file used to build supported packages.
#
# Copyright (c) Microsoft Corporation.
# Copyright (c) 2020 - 2021, ARM Limited. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

parameters:
  tool_chain_tag: ''
  vm_image: ''
  arch_list: ''
  extra_steps: []   # MU_CHANGE
  build_args: ''    # MU_CHANGE - Allow environment level build args.

# Build step
jobs:

- job: Build_${{ parameters.tool_chain_tag }}
  timeoutInMinutes: 120
  #Use matrix to speed up the build process
  strategy:
    matrix:
      TARGET_DFCI_ZERO_XML:
        Build.Pkgs: 'DfciPkg,ZeroTouchPkg,XmlSupportPkg,MfciPkg'
        Build.Targets: 'DEBUG,RELEASE,NO-TARGET,NOOPT'
      TARGET_GRAPHICS:
        Build.Pkgs: 'MsGraphicsPkg'
        Build.Targets: 'DEBUG,RELEASE,NO-TARGET,NOOPT'
      TARGET_CORE:
        Build.Pkgs: 'MsCorePkg'
        Build.Targets: 'DEBUG,RELEASE,NO-TARGET,NOOPT'
      TARGET_TEST_PCBDS_LOG_WHEA_HID:
        Build.Pkgs: 'UefiTestingPkg,PcBdsPkg,AdvLoggerPkg,MsWheaPkg,HidPkg'
        Build.Targets: 'DEBUG,RELEASE,NO-TARGET,NOOPT'
  workspace:
    clean: all

  pool:
    vmImage: ${{ parameters.vm_image }}

  steps:
  - template: pr-gate-steps.yml
    parameters:
      tool_chain_tag: ${{ parameters.tool_chain_tag }}
      build_pkgs: $(Build.Pkgs)
      build_targets: $(Build.Targets)
      build_archs: ${{ parameters.arch_list }}
      extra_steps: ${{ parameters.extra_steps }}   # MU_CHANGE
      build_args: ${{ parameters.build_args }}     # MU_CHANGE
      has_ci_dependencies: true
