## @file
# codecov upload configuration file to carryforward coverage results of
# packages that do not upload coverage results for a given pull request.
##
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
flags:
  AdvLoggerPkg:
    carryforward: true
  HidPkg:
    carryforward: true
  MfciPkg:
    carryforward: true
  MsApplicationPkg:
    carryforward: true
  MsCorePkg:
    carryforward: true
  MsGraphicsPkg:
    carryforward: true
  MsWheaPkg:
    carryforward: true
  PcBdsPkg:
    carryforward: true
  TpmTestingPkg:
    carryforward: true
  UefiTestingPkg:
    carryforward: true
  XmlSupportPkg:
    carryforward: true

