[target.x86_64-unknown-uefi]
rustflags = [
    "-C", "link-arg=/base:0x0",
    "-C", "link-arg=/subsystem:efi_application",
]

[target.i686-unknown-uefi]
rustflags = [
    "-C", "link-arg=/base:0x0",
    "-C", "link-arg=/subsystem:efi_boot_service_driver",
    "-C", "link-arg=/subsystem:efi_application",
]

[target.aarch64-unknown-uefi]
rustflags = [
    "-C", "link-arg=/base:0x0",
    "-C", "link-arg=/subsystem:efi_boot_service_driver",
]

[registries]
patina-fw = { index = "sparse+https://pkgs.dev.azure.com/patina-fw/artifacts/_packaging/temporary/Cargo/index/" }